### ISSUE TITLE
System.IO.FileNotFoundException: could not load...“System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”

### ISSUE THREAD

**Issue by nevernet** [mkjeff/secs4net#41]
@a-v-kalabuhov @kyunggyuyeol  

i got an issue which is that "system.memory version=4.0.1" could not be loaded.
details info as below: 

```
System.IO.FileNotFoundException: could not load...“System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”
Filename:“System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”
   at Secs4Net.StreamDecoder.<.ctor>g__GetMessageHeader|23_1(Int32& length, Int32& need)
   at Secs4Net.StreamDecoder.<.ctor>g__GetTotalMessageLength|23_0(Int32& length, Int32& need)
   at Secs4Net.StreamDecoder.Decode(Int32 length)
   at Secs4Net.SecsGem.<.ctor>g__SocketReceiveEventCompleted|84_9(Object sender, SocketAsyncEventArgs e)
```

the vs2017 has been updated system.memory version to 4.5.3 in csproj file.

secs4net project info: 
target framework: .Net Standard 2.0
vs 2017

any ideas will be appreciated.
thank you

**Comment by nevernet** [comment]
the issue has been solved. we have to specify the System.Memory version in project "SecsDevice", and it will override the default System.Memory verson
