### ISSUE TITLE
10053 error

### ISSUE THREAD

**Issue by 5008748168** [mkjeff/secs4net#71]
**Describe the bug**
When connect remote device, got 10053 error.

022-10-13 10:42:13.595 +08:00 [INF] Starting host
2022-10-13 10:42:18.183 +08:00 [WRN] Connecting
2022-10-13 10:42:18.202 +08:00 [WRN] Connected
2022-10-13 10:42:18.214 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2022-10-13 10:42:18.229 +08:00 [INF] Hosting environment: Production
2022-10-13 10:42:19.462 +08:00 [INF] Start T7 Timer: 10 sec.
2022-10-13 10:42:25.145 +08:00 [INF] Content root path: C:\新建文件夹\FN03\KuoSan\HongTaiYang\FN-03-L1-A
2022-10-13 10:42:30.745 +08:00 [INF] Sent Control Message: SelectRequest
2022-10-13 10:42:30.947 +08:00 [ERR] Unhandled exception occurred on PipeDecoder producer 

System.Net.Sockets.SocketException (10053): 你的主机中的软件中止了一个已建立的连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at Secs4Net.HsmsConnection.StartPipeDecoderProducerAsync(CancellationToken cancellation)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Secs4Net.HsmsConnection.StartPipeDecoderProducerAsync(CancellationToken cancellation)
   at Secs4Net.HsmsConnection.<>c__DisplayClass65_0.<CommunicationStateChanging>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at Secs4Net.HsmsConnection.StartPipeDecoderProducerAsync(CancellationToken cancellation)
2022-10-13 10:42:30.952 +08:00 [ERR] Connection loss, try to reconnect.
2022-10-13 10:42:30.957 +08:00 [WRN] Connecting
2022-10-13 10:42:30.966 +08:00 [WRN] Connected
2022-10-13 10:42:30.969 +08:00 [INF] Start T7 Timer: 10 sec.
2022-10-13 10:42:30.971 +08:00 [INF] Sent Control Message: SelectRequest
2022-10-13 10:42:30.979 +08:00 [ERR] Unhandled exception occurred on PipeDecoder producer 

System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at Secs4Net.HsmsConnection.StartPipeDecoderProducerAsync(CancellationToken cancellation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ThreadPool.<>c.<.cctor>b__87_0(Object state)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__179_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---
   at Secs4Net.HsmsConnection.StartPipeDecoderProducerAsync(CancellationToken cancellation)
2022-10-13 10:42:30.982 +08:00 [ERR] Connection loss, try to reconnect.
2022-10-13 10:42:30.990 +08:00 [WRN] Connecting
2022-10-13 10:42:30.999 +08:00 [WRN] Connected
2022-10-13 10:42:31.053 +08:00 [INF] Start T7 Timer: 10 sec.
2022-10-13 10:42:36.376 +08:00 [ERR] T6 Timeout[id=0x4D519F9E]: 5 sec. 

2022-10-13 10:42:36.376 +08:00 [ERR] T6 Timeout[id=0x4D519F9D]: 5 sec. 

2022-10-13 10:42:42.426 +08:00 [INF] Sent Control Message: SelectRequest
2022-10-13 10:42:42.427 +08:00 [ERR] Connection loss, try to reconnect.
2022-10-13 10:42:42.429 +08:00 [ERR] Connection loss, try to reconnect.
2022-10-13 10:42:42.434 +08:00 [WRN] Connecting
2022-10-13 10:42:42.450 +08:00 [WRN] Connecting
2022-10-13 10:42:42.458 +08:00 [WRN] Connected
2022-10-13 10:42:42.462 +08:00 [WRN] Connected
2022-10-13 10:42:42.472 +08:00 [INF] Start T7 Timer: 10 sec.
2022-10-13 10:42:42.472 +08:00 [ERR] Unexpected exception on StartAsyncStreamDecoderAsync 

System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.TryRead(ReadResult& result)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.TryRead(ReadResult& result)
   at Secs4Net.PipeDecoder.DecodeLoopAsync(ChannelWriter`1 controlMessageWriter, ChannelWriter`1 dataMessageWriter, PipeReader reader, CancellationToken cancellation)
   at Secs4Net.HsmsConnection.StartPipeDecoderConsumerAsync(CancellationToken cancellation)
2022-10-13 10:42:42.473 +08:00 [INF] Start T7 Timer: 10 sec.
2022-10-13 10:42:47.615 +08:00 [ERR] T6 Timeout[id=0x4D519F9F]: 5 sec.

**Comment by 5008748168** [comment]
**CPU usage is High(100%) When 10053 error happened.**

As a host, HsmsConnection class will always try to reconnect device when socket closed. 
No  any **Retry police** applied. 

I think it's a bug.
