### ISSUE TITLE
Sometimes the message reading is incomplete.

### ISSUE THREAD

**Issue by eacanchen** [mkjeff/secs4net#85]
<-- [0x000006B0] 'S6F11'W
    <L [3] 
        <A [4] '9000'>
        <A [4] '8001'>
        <L [1] 
            <L [2] 
                <U2 [1] 801>
                <L [2] 
                    <A [4] 'test'>
                    <A [3] 'eqp'>
                >
            >
        >
    >
.

--> [0x000006B0] 'S6F12'
    <B [1] 0x00>
.

<-- [0x000006B1] 'S6F11'W
    <L [0] 
    >
.

--> [0x000006B1] 'S6F12'
    <B [1] 0x00>
.

Unexpected exception on StartAsyncStreamDecoderAsync

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Secs4Net.Item.<DecodeDataItem>g__ThrowHelper|45_14(ReadOnlySequence`1& _) in /_/src/Secs4Net/Item.Decode.cs:line 457
   at Secs4Net.PipeDecoder.DecodeLoopAsync(ChannelWriter`1 controlMessageWriter, ChannelWriter`1 dataMessageWriter, PipeReader reader, CancellationToken cancellation) in /_/src/Secs4Net/PipeDecoder.cs:line 159
   at Secs4Net.HsmsConnection.StartPipeDecoderConsumerAsync(CancellationToken cancellation) in /_/src/Secs4Net/HsmsConnection.cs:line 261

**Comment by wang9th** [comment]
我也遇到了这个问题，你解决了吗？

**Comment by eacanchen** [comment]
解决了，尝试放大缓存区

**Comment by wang9th** [comment]
> 

buffer size 设置为多少？会不会暂时测试不报错，长时间就会出现

**Comment by wang9th** [comment]
> 解决了，尝试放大缓存区
我 用 fastsim 与 这个项目 自带 的 样例 通讯时，buffer size 设置为 5120，他 不会立即出现问题，使用一段时间后才会出现

**Comment by wang9th** [comment]
> 解决了，尝试放大缓存区

放大缓冲区后你还遇到过这个问题吗？
